spring:
  sql:
    init:
      mode: never


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    arg-name-based-constructor-auto-mapping: true

logging:
  level:
    org:
      springframework:
        security: INFO
        transaction:
          interceptor: TRACE


vault:
  scheme: http
  uri: 3.22.218.43
  token: hvs.frFvDB3V7L4UYrBlQ6fFvBtD
  port: 8200