spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      maximum-pool-size: 20


  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: embedded

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    arg-name-based-constructor-auto-mapping: true

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
        security: ERROR

vault:
  scheme: http
  uri: 3.22.218.43ㅠ
  token: hvs.frFvDB3V7L4UYrBlQ6fFvBtD
  port: 8200