spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    arg-name-based-constructor-auto-mapping: true

logging:
  level:
    org:
      springframework:
        transaction: TRACE
        security: INFO

vault:
  scheme: http
  uri: host.docker.internal
  token: hvs.frFvDB3V7L4UYrBlQ6fFvBtD
  port: 8200