spring:
  jmx:
    enabled: false

logging:
  level:
    org:
      springframework:
        context: DEBUG
        security: INFO
      mybatis: DEBUG

vault:
  scheme: http
  uri: 3.22.218.43
  token: hvs.frFvDB3V7L4UYrBlQ6fFvBtD
  port: 8200
