spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    enabled: false

mybatis:
  mapper-locations:
    - classpath:mapper/basic/*.xml
    - classpath:mapper/lock-mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    arg-name-based-constructor-auto-mapping: true

logging:
  level:
    org:
      springframework:
        security: INFO
        transaction:
          interceptor: TRACE


vault:
  scheme: http
  uri: host.docker.internal
  token: hvs.frFvDB3V7L4UYrBlQ6fFvBtD
  port: 8200