spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    arg-name-based-constructor-auto-mapping: true

logging:
  level:
    org:
      springframework:
        security: INFO

vault:
  scheme: http
  uri: localhost
  token: 00000000-0000-0000-0000-000000000000
  port: 8200