spring:
  sql:
    init:
      mode: never
  jmx:
    enabled: false

logging:
  level:
    org:
      springframework:
        transaction: TRACE
        security: INFO

vault:
  scheme: http
  uri: host.docker.internal
  token: hvs.frFvDB3V7L4UYrBlQ6fFvBtD
  port: 8200